name: HA Remote Bridge
version: "0.4.12"
slug: ha_remote_bridge
description: Securely access selected local HTTP/HTTPS, SSH, VNC and SMB resources through Home Assistant Ingress.
url: https://github.com/ricobach/HA-Remote-Bridge
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
stage: experimental
host_network: true
ingress: true
ingress_port: 8099
panel_icon: mdi:lan-connect
panel_title: Remote Bridge
panel_admin: true
